"""
This is the External wrapper for handling the Graphical User Interface(GUI) 

Generated By Matthew Larson on November 8th 2023
"""

import dearpygui.dearpygui as dpg 
from hfwmSetup import *
from stageControl import *

dpg.create_context()
dpg.create_viewport(title='Main Context',width=1200,height=600)

with dpg.window(label='Stage Control Window'):
    #setup control 
    dpg.add_text('Stage Control')
    dpg.add_combo(['k1','k2','k3'],label='Select Stage',callback=stageselect)
    dpg.add_button(label='Zero Stage',callback=zerostage)
    dpg.add_button(label='Get Position',callback=getposition)
    
    #motion control    
    dpg.add_double_value(label='Stage Position')
    dpg.add_button(label='Move Stage',callback=movestage)
    
with dpg.window(label="HFWM Setup"):
    dpg.add_combo(['k1','k2','k3'],label='Select Stage a',callback=stageselecta,default_value=0)
    dpg.add_combo(['k1','k2','k3'],label='Select Stage b',callback=stageselectb,default_value=2)
#with dpg.window(label="HFWM Data Monitor"):
    


dpg.setup_dearpygui()
dpg.show_viewport()
#dpg.set_primary_window(window=0,value=True)
dpg.start_dearpygui()
dpg.destroy_context()