"""
This is the internal wrapper for handling Stage controll call backs 

Generated By Matthew Larson on November 8th 2023
"""

import dearpygui.dearpygui as dpg 
def stageselect(sender,data):
    """handle stage selection for stage control window
    """
    print(sender," returned: ", dpg.get_value(sender))

def zerostage(sender,data):
    """handle stage zeroing for stage control window
    """
    print("stage zero called value:",dpg.get_value(sender))

def getposition(sender,data):
    """retrieve current position for stage """
    print("get position called value returned of")