"""
This is the internal wrapper for handling Stage controll call backs 

Generated By Matthew Larson on November 8th 2023
"""

import dearpygui.dearpygui as dpg 

def zerostage(sender,data,userdata):
    """handle stage zeroing for stage control window
    """
    dpg.set_value(userdata[1],"Stage status: Zeroing")
    dpg.set_value(userdata[0],'Current Position: 0')
    print("stage zero called value:",dpg.get_value(sender))
    dpg.set_value(userdata[1],"Stage status: inactive")

def getposition(sender,data,userdata):
    """retrieve current position for stage """
    dpg.set_value(userdata[1],"Stage status: Position Query")
    dpg.set_value(userdata[0],'Current Position: 50')
    print("get position called value returned of")
    dpg.set_value(userdata[1],"Stage status: inactive")
    

def movestage(sender,data,userdata):
    """move stage to position set in box for"""
    dpg.set_value(userdata[6],"Stage status: Moving")
    print("stage",dpg.get_value(userdata[2])," moving to",dpg.get_value(userdata[0]),
          dpg.get_value(userdata[3]),'at',dpg.get_value(userdata[4]),dpg.get_value(userdata[5]) )
    dpg.set_value(userdata[1],"Current Position: "+str(dpg.get_value(userdata[0])))
    print("motion complete")
    dpg.set_value(userdata[6],"Stage status: inactive")